language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t gabeso/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gabeso/docker-react npm run test

